# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Munchys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Munchys
     pod 'AWSCloudWatch'
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSDynamoDB'
     pod 'AWSLambda'
     pod 'AWSMobileAnalytics'
     pod 'AWSS3'

end
